/**
 * Parity test for the in-process citation converter (src/convertCitations.ts),
 * which must behave exactly like scripts/convert-citations.mjs. The expected
 * outputs below were generated by running that script on the same inputs.
 */
import {
  REFERENCE_BODY_STYLE,
  collectReferenceKeys,
  convertCitationsInText,
  substituteReferenceInsertions,
} from '../convertCitations';

const refBlock = (entry: string) =>
  `::: {custom-style="${REFERENCE_BODY_STYLE}"}\n${entry}\n:::`;

describe('convertCitationsInText', () => {
  const cases: [string, string][] = [
    ['[[@smith2020]]', '[@smith2020]'],
    ['[[@key|@]]', '[@key]'],
    ['[[@smith2020|see @, p. 6]]', '[see @smith2020, p. 6]'],
    ['[[@key|-@, p. 6]]', '[-@key, p. 6]'],
    ["[[@smith2020|Smith's work]]", "Smith's work [@smith2020]"],
    ['[ [[@a]]; [[@b]] ]', '[@a; @b]'],
    ['[ see also [[@a]]; [[@b]] ]', '[@a; @b]'],
    ['[ [[@a]]; [@b, p. 5] ]', '[@a; @b, p. 5]'],
    ['[[@key|@ -]]', '@key'],
    ['[[@key|see @ -]]', 'see @key'],
    ['[[@key|-@]]', '[-@key]'],
    ['[ [[@a|@ -]]; [[@b]] ]', '@a [@b]'],
    ['[ [[@a]]; [[@b|@ -]] ]', '[@a; @b]'],
    ['[[@a|@, vol. I, p. 113]]', '[@a, 1:113]'],
    // Every volume synonym combines to the single Chicago locator (export
    // parity with the live parser — see parser.test.ts).
    ['[[@a|@, v. 2, p. 200–201]]', '[@a, 2:200–201]'],
    ['[[@a|@, volume 2, p. 200–201]]', '[@a, 2:200–201]'],
    ['[[@a|@, vols. 2, p. 200–201]]', '[@a, 2:200–201]'],
    // Forced-locator block in a NARRATIVE alias: the bracket content mirrors a
    // normal citation's after-comma content, so the braces are KEPT inside the
    // author-in-text bracket (`@a [{…}]`) and citeproc still honours them.
    ['[[@a|@{, vol. 2, p. 41–43} -]]', '@a [{, 2:41–43}]'],
    ['[[@a|@{vol. 2, p. 41–43} -]]', '@a [{2:41–43}]'],
    ['[[@a|@{ii, A, D-Z} -]]', '@a [{ii, A, D-Z}]'],
    ['[[@a|@{ii, A, D-Z}, with a suffix]]', '[@a{ii, A, D-Z}, with a suffix]'],
    ['[[@a|@{}, 99 years later]]', '[@a{}, 99 years later]'],
    ['plain [[note name]] link', 'plain [[note name]] link'],
  ];

  it.each(cases)('%s → %s', (input, expected) => {
    expect(convertCitationsInText(input)).toBe(expected);
  });

  it('converts each line independently and preserves line structure', () => {
    const input = 'Intro [[@a]].\n\n- item [[@b|@, p. 2]]\n\nplain line';
    expect(convertCitationsInText(input)).toBe(
      'Intro [@a].\n\n- item [@b, p. 2]\n\nplain line'
    );
  });
});

describe('full-reference insertions (export pre-render)', () => {
  it('collects the citekeys of reference insertions', () => {
    expect(collectReferenceKeys('[[@a|reference]] and [[@b|@, p. 2]]')).toEqual([
      'a',
    ]);
    expect(
      collectReferenceKeys('[ [[@a|reference]] [[@b]] [[@c]] ]')
    ).toEqual(['a', 'b', 'c']);
    // A contiguous run with any `ref` member is one reference list -> both keys.
    expect(collectReferenceKeys('[[@a]] [[@b|ref]]')).toEqual(['a', 'b']);
  });

  it('substitutes each insertion with a styled reference block', () => {
    const lookup = (k: string) => `[ENTRY ${k}]`;
    // Each entry becomes its own custom-style block (blank lines around it so
    // pandoc parses it as a block even when the insertion was inline).
    expect(
      substituteReferenceInsertions('See [[@a|reference]].', lookup)
    ).toBe(`See \n\n${refBlock('[ENTRY a]')}\n\n.`);

    // A container renders one entry per block (text outside is discarded).
    expect(
      substituteReferenceInsertions(
        '[ [[@a|reference]] [[@b]] [[@c]] ]',
        lookup
      )
    ).toBe(
      `\n\n${refBlock('[ENTRY a]')}\n\n${refBlock('[ENTRY b]')}\n\n${refBlock(
        '[ENTRY c]'
      )}\n\n`
    );
  });

  it('substitutes a CONTIGUOUS reference run (no container) as one list', () => {
    // Any `reference` member turns the whole adjacent run into a list; the
    // whole run must be replaced (regression: only the first member's range
    // was replaced, leaving `[[@b]] [[@c]]` behind).
    const lookup = (k: string) => `[ENTRY ${k}]`;
    expect(
      substituteReferenceInsertions('See [[@a|reference]] [[@b]] [[@c]].', lookup)
    ).toBe(
      `See \n\n${refBlock('[ENTRY a]')}\n\n${refBlock(
        '[ENTRY b]'
      )}\n\n${refBlock('[ENTRY c]')}\n\n.`
    );
  });

  it('leaves ordinary citations for the standard converter', () => {
    const withRefs = substituteReferenceInsertions(
      '[[@a|reference]] then [[@b|@, p. 2]]',
      (k) => `[${k}]`
    );
    expect(withRefs).toContain(refBlock('[a]'));
    expect(withRefs).toContain('then [[@b|@, p. 2]]');
    expect(convertCitationsInText(withRefs)).toContain('then [@b, p. 2]');
  });
});

describe('convertCitationsInText() — contiguous citations merge', () => {
  it('merges adjacent citations into one pandoc citation', () => {
    expect(convertCitationsInText('[[@a]] [[@b]]')).toBe('[@a; @b]');
    expect(convertCitationsInText('[[@a]]\n[[@b]]')).toBe('[@a; @b]');
    expect(convertCitationsInText('[[@a]] [@b] [[@c]]')).toBe('[@a; @b; @c]');
  });

  it('does not merge across a blank line or with text between', () => {
    expect(convertCitationsInText('[[@a]]\n\n[[@b]]')).toBe('[@a]\n\n[@b]');
    expect(convertCitationsInText('[[@a]] and [[@b]]')).toBe('[@a] and [@b]');
  });

  it('does not merge a bare narrative citation', () => {
    expect(convertCitationsInText('[[@a|@ -]] [[@b]]')).toBe('@a [@b]');
  });
});
