/**
 * Parity test for the in-process citation converter (src/convertCitations.ts),
 * which must behave exactly like scripts/convert-citations.mjs. The expected
 * outputs below were generated by running that script on the same inputs.
 */
import {
  collectReferenceKeys,
  convertCitationsInText,
  substituteReferenceInsertions,
} from '../convertCitations';

describe('convertCitationsInText', () => {
  const cases: [string, string][] = [
    ['[[@smith2020]]', '[@smith2020]'],
    ['[[@key|@]]', '[@key]'],
    ['[[@smith2020|see @, p. 6]]', '[see @smith2020, p. 6]'],
    ['[[@key|-@, p. 6]]', '[-@key, p. 6]'],
    ["[[@smith2020|Smith's work]]", "Smith's work [@smith2020]"],
    ['[ [[@a]]; [[@b]] ]', '[@a; @b]'],
    ['[ see also [[@a]]; [[@b]] ]', '[@a; @b]'],
    ['[ [[@a]]; [@b, p. 5] ]', '[@a; @b, p. 5]'],
    ['[[@key|@ -]]', '@key'],
    ['[[@key|see @ -]]', 'see @key'],
    ['[[@key|-@]]', '[-@key]'],
    ['[ [[@a|@ -]]; [[@b]] ]', '@a [@b]'],
    ['[ [[@a]]; [[@b|@ -]] ]', '[@a; @b]'],
    ['[[@a|@, vol. I, p. 113]]', '[@a, 1:113]'],
    ['plain [[note name]] link', 'plain [[note name]] link'],
  ];

  it.each(cases)('%s → %s', (input, expected) => {
    expect(convertCitationsInText(input)).toBe(expected);
  });

  it('converts each line independently and preserves line structure', () => {
    const input = 'Intro [[@a]].\n\n- item [[@b|@, p. 2]]\n\nplain line';
    expect(convertCitationsInText(input)).toBe(
      'Intro [@a].\n\n- item [@b, p. 2]\n\nplain line'
    );
  });
});

describe('full-reference insertions (export pre-render)', () => {
  it('collects the citekeys of reference insertions', () => {
    expect(collectReferenceKeys('[[@a|reference]] and [[@b|@, p. 2]]')).toEqual([
      'a',
    ]);
    expect(
      collectReferenceKeys('[ [[@a|reference]] [[@b]] [[@c]] ]')
    ).toEqual(['a', 'b', 'c']);
    expect(collectReferenceKeys('[[@a]] [[@b|ref]]')).toEqual(['b']);
  });

  it('substitutes each insertion with its pre-rendered text', () => {
    const lookup = (k: string) => `[ENTRY ${k}]`;
    expect(
      substituteReferenceInsertions('See [[@a|reference]].', lookup)
    ).toBe('See [ENTRY a].');

    // A container renders one entry per paragraph (text outside is discarded).
    expect(
      substituteReferenceInsertions(
        '[ [[@a|reference]] [[@b]] [[@c]] ]',
        lookup
      )
    ).toBe('[ENTRY a]\n\n[ENTRY b]\n\n[ENTRY c]');
  });

  it('leaves ordinary citations for the standard converter', () => {
    const withRefs = substituteReferenceInsertions(
      '[[@a|reference]] then [[@b|@, p. 2]]',
      (k) => `[${k}]`
    );
    expect(withRefs).toBe('[a] then [[@b|@, p. 2]]');
    expect(convertCitationsInText(withRefs)).toBe('[a] then [@b, p. 2]');
  });
});
