import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import fs from "fs";
import crypto from "crypto";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Resolve "src/..." imports as if the project root contains a "src" directory.
// Mirrors TypeScript "paths": { "src/*": ["./src/*"] } without tsconfig.
// Reads every file in scripts/, sw-export-templates/, docs/, images/ and the
// opt-in template folders at build time and exposes them
// as a virtual module `bundled:assets`. Text files are stored as UTF-8
// strings; binary files (docx, odt) are stored as base64 strings. The plugin
// runtime (src/assetSetup.ts) decodes and writes them to the plugin directory
// on first load / version change so non-technical users never have to touch
// GitHub manually.
const bundleAssetsPlugin = {
	name: 'bundle-assets',
	setup(build) {
		build.onResolve({ filter: /^bundled:assets$/ }, (args) => ({
			path: args.path,
			namespace: 'bundled-assets-ns',
		}));

		build.onLoad({ filter: /.*/, namespace: 'bundled-assets-ns' }, async () => {
			const binaryExts = new Set(['.docx', '.odt', '.pdf', '.png', '.jpg', '.jpeg']);
			const skipPrefixes = ['__', '.'];
			const assets = {};

			// Content hash, embedded alongside each asset so the runtime can
			// extract only the files whose bytes actually changed instead of
			// rewriting the whole asset set on every plugin load.
			const hashOf = (buf) =>
				crypto.createHash('sha256').update(buf).digest('hex').slice(0, 16);

			const readFile = async (rel) => {
				const fullPath = path.resolve(__dirname, rel);
				if (!fs.existsSync(fullPath) || !fs.statSync(fullPath).isFile()) return;
				const ext = path.extname(rel).toLowerCase();
				const buf = fs.readFileSync(fullPath);
				assets[rel] = {
					content: binaryExts.has(ext) ? buf.toString('base64') : buf.toString('utf-8'),
					binary: binaryExts.has(ext),
					hash: hashOf(buf),
				};
			};

			const readDir = async (subdir) => {
				const dir = path.resolve(__dirname, subdir);
				if (!fs.existsSync(dir)) return;
				for (const file of fs.readdirSync(dir)) {
					if (skipPrefixes.some((p) => file.startsWith(p))) continue;
					const fullPath = path.join(dir, file);
					if (!fs.statSync(fullPath).isFile()) continue;
					const ext = path.extname(file).toLowerCase();
					const buf = fs.readFileSync(fullPath);
					assets[`${subdir}/${file}`] = {
						content: binaryExts.has(ext) ? buf.toString('base64') : buf.toString('utf-8'),
						binary: binaryExts.has(ext),
						hash: hashOf(buf),
					};
				}
			};

			await readDir('scripts');
			await readDir('sw-export-templates');
			// Callout icon PNGs (one neutral black/transparent icon per type),
			// extracted to the plugin dir so sw-callouts.lua can reference them
			// as images. See tools/gen-callout-icons.py.
			await readDir('icons');
			// User-facing docs — bundled as UTF-8 strings so the settings modal
			// can render them in-app (src/docs.ts). NOT extracted to the plugin
			// dir (see assetSetup.ts).
			await readDir('docs');
			// README (rendered as the docs "Overview" page) + NOTICE + images.
			await readFile('README.md');
			await readFile('NOTICE.md');
			await readDir('images');
			// ZotLit import templates — bundled so the "Install ScholarWeft's
			// ZotLit templates" button in settings can write them into the
			// vault. NOT auto-extracted to the plugin dir (see assetSetup.ts).
			await readDir('sw-zotlit-templates');
			// ZotLit import SETTINGS (frontmatter field mappings). ZotLit's
			// frontmatter is driven by its data.json, not by the templates, so
			// the templates alone don't reproduce the import output; the install
			// button writes these mappings into ZotLit's settings.
			await readDir('sw-zotlit-settings');
			// Basic note template — bundled so the "Install the Basic note
			// template and set up Templater" button in settings can write it
			// into the vault. NOT auto-extracted to the plugin dir.
			await readDir('sw-markdown-templates');

			return {
				contents: `export const BUNDLED_ASSETS = ${JSON.stringify(assets)};`,
				loader: 'js',
			};
		});
	},
};

const srcAliasPlugin = {
	name: "src-alias",
	setup(build) {
		build.onResolve({ filter: /^src\// }, (args) => {
			const relative = args.path.slice(4); // strip "src/"
			const base = path.resolve(__dirname, "src", relative);

			// Probe candidate paths in priority order.
			const candidates = [
				base,            // exact (if someone wrote the extension)
				base + ".ts",
				base + ".tsx",
				base + ".js",
				path.join(base, "index.ts"),
				path.join(base, "index.tsx"),
				path.join(base, "index.js"),
			];

			for (const candidate of candidates) {
				if (fs.existsSync(candidate)) {
					return { path: candidate };
				}
			}

			// Couldn't resolve — return the bare path so esbuild emits a
			// useful "could not read file" error pointing at the right location.
			return { path: base + ".ts" };
		});
	},
};

const options = {
	banner: {
		js: banner,
	},
	entryPoints: [path.resolve(__dirname, "src/main.ts")],
	absWorkingDir: __dirname,
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [srcAliasPlugin, bundleAssetsPlugin],
};

if (prod) {
	await esbuild.build(options);
	process.exit(0);
} else {
	await esbuild.build({ ...options, watch: true });
}
