#!/usr/bin/env python3
"""Add the Obsidian callout paragraph styles to the export templates.

Creates one paragraph style per STANDARD Obsidian callout type, all children of
a base `callout` style, overriding ONLY the background colour so the whole
family is restyled from one place.  The base style is copied from document.docx
/ document.odt when a target template doesn't already define it.

Obsidian's default colours are used: the background is the type colour at 10%
over white (Obsidian's own `rgba(--callout-color, 0.1)`).

Style names are `Callout <Type>` — the aliases (summary, hint, check, …) map
onto these in scripts/sw-callouts.lua, which must stay in sync with CALLOUTS
here.  The matching icon PNGs are generated by tools/gen-callout-icons.py.

Run from anywhere:  python3 tools/add-callout-styles.py [template ...]
(no args = all bundled templates)
"""
import copy
import shutil
import sys
import zipfile
from pathlib import Path
from lxml import etree

ROOT = Path(__file__).resolve().parent.parent
TPL = ROOT / 'sw-export-templates'

W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
S = 'urn:oasis:names:tc:opendocument:xmlns:style:1.0'
O = 'urn:oasis:names:tc:opendocument:xmlns:office:1.0'
F = 'urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0'


def w(t): return '{%s}%s' % (W, t)
def s(t): return '{%s}%s' % (S, t)
def o(t): return '{%s}%s' % (O, t)
def f(t): return '{%s}%s' % (F, t)


# canonical type -> full RGB (Obsidian default app.css values)
CALLOUTS = [
    ('Note',     '448AFF'),
    ('Abstract', '00B0FF'),
    ('Info',     '00B8D4'),
    ('Todo',     '00B8D4'),
    ('Tip',      '00BFA5'),
    ('Success',  '08B94E'),
    ('Question', 'EC7500'),
    ('Warning',  'EC7500'),
    ('Failure',  'E93147'),
    ('Danger',   'E93147'),
    ('Bug',      'E93147'),
    ('Example',  '7852EE'),
    ('Quote',    '9E9E9E'),
]


def tint(hexcolor, alpha=0.1):
    r, g, b = (int(hexcolor[i:i + 2], 16) for i in (0, 2, 4))
    mix = lambda c: round(255 * (1 - alpha) + c * alpha)
    return '%02X%02X%02X' % (mix(r), mix(g), mix(b))


# ── DOCX ─────────────────────────────────────────────────────────────────────

def _docx_base(root):
    return next((st for st in root.findall(w('style'))
                 if st.get(w('styleId')) == 'callout'), None)


def add_docx(path, base_src):
    with zipfile.ZipFile(path) as z:
        data = {n: z.read(n) for n in z.namelist()}
    root = etree.fromstring(data['word/styles.xml'])
    base = _docx_base(root)
    if base is None:                       # borrow the base from document.docx
        with zipfile.ZipFile(base_src) as z:
            src_root = etree.fromstring(z.read('word/styles.xml'))
        src_base = _docx_base(src_root)
        if src_base is None:
            sys.exit('no base "callout" style in %s' % base_src)
        base = etree.fromstring(etree.tostring(src_base))
        normal = next((st for st in root.findall(w('style'))
                       if st.get(w('styleId')) == 'Normal'), None)
        (normal.addnext(base) if normal is not None else root.append(base))

    for name, colour in CALLOUTS:
        sid = 'Callout' + name
        for old in root.findall(w('style')):     # replace on re-run
            if old.get(w('styleId')) == sid:
                root.remove(old)
        st = etree.Element(w('style'))
        st.set(w('type'), 'paragraph')
        st.set(w('styleId'), sid)
        etree.SubElement(st, w('name')).set(w('val'), 'Callout ' + name)
        etree.SubElement(st, w('basedOn')).set(w('val'), 'callout')
        etree.SubElement(st, w('qFormat'))
        ppr = etree.SubElement(st, w('pPr'))
        # Background AND border colour from the type.  A child `w:pBdr`
        # REPLACES the parent's, so copy the base's border (width, style,
        # border-space/padding, shadow) and change ONLY the colour — otherwise
        # the child freezes those values and diverges when the base changes.
        # Same for `w:shd`: copy the base's and change only the fill.  Spacing/
        # indent/contextual-spacing are left to inherit from the base.
        base_ppr = base.find(w('pPr'))
        base_pbdr = base_ppr.find(w('pBdr')) if base_ppr is not None else None
        if base_pbdr is not None:
            pbdr = copy.deepcopy(base_pbdr)
            for side in pbdr:
                side.set(w('color'), colour)
            ppr.append(pbdr)
        base_shd = base_ppr.find(w('shd')) if base_ppr is not None else None
        if base_shd is not None:
            shd = copy.deepcopy(base_shd)
        else:
            shd = etree.Element(w('shd'))
            shd.set(w('val'), 'clear')
            shd.set(w('color'), 'auto')
        shd.set(w('fill'), tint(colour))
        ppr.append(shd)
        base.addnext(st)
    data['word/styles.xml'] = etree.tostring(
        root, xml_declaration=True, encoding='UTF-8', standalone=True)
    _rewrite_zip(path, data)
    print('DOCX %s: %d callout styles' % (path.name, len(CALLOUTS)))


# ── ODT ──────────────────────────────────────────────────────────────────────

def _odt_base(root):
    return next((st for st in root.iter(s('style'))
                 if st.get(s('name')) == 'callout'), None)


def add_odt(path, base_src):
    with zipfile.ZipFile(path) as z:
        data = {n: z.read(n) for n in z.namelist()}
    root = etree.fromstring(data['styles.xml'])
    base = _odt_base(root)
    if base is None:                       # borrow the base from document.odt
        with zipfile.ZipFile(base_src) as z:
            src_root = etree.fromstring(z.read('styles.xml'))
        src_base = _odt_base(src_root)
        if src_base is None:
            sys.exit('no base "callout" style in %s' % base_src)
        base = etree.fromstring(etree.tostring(src_base))
        root.find(o('styles')).append(base)

    for name, colour in CALLOUTS:
        sname = 'Callout_20_' + name
        for old in root.iter(s('style')):        # replace on re-run
            if old.get(s('name')) == sname:
                old.getparent().remove(old)
                break
        st = etree.Element(s('style'))
        st.set(s('name'), sname)
        st.set(s('display-name'), 'Callout ' + name)
        st.set(s('family'), 'paragraph')
        st.set(s('parent-style-name'), 'callout')
        pp = etree.SubElement(st, s('paragraph-properties'))
        # Background AND border colour from the type.  The base's PADDING is
        # copied explicitly: LibreOffice materialises a bordered paragraph
        # style's "spacing to contents" as 0 on save and does NOT inherit the
        # parent's padding, so leaving it out silently removes the callout's
        # padding.  Indents/margins/spacing are left to inherit (LO keeps
        # those).  Re-run this tool after changing the base's padding.
        pp.set(f('background-color'), '#' + tint(colour))
        pp.set(f('border'), '0.02cm solid #%s' % colour)
        base_pp = base.find(s('paragraph-properties'))
        if base_pp is not None:
            for attr in (f('padding'), f('padding-top'), f('padding-right'),
                         f('padding-bottom'), f('padding-left')):
                val = base_pp.get(attr)
                if val is not None:
                    pp.set(attr, val)
        base.addnext(st)
    data['styles.xml'] = etree.tostring(
        root, xml_declaration=True, encoding='UTF-8', standalone=True)
    _rewrite_zip(path, data)
    print('ODT %s: %d callout styles' % (path.name, len(CALLOUTS)))


def _rewrite_zip(path, data):
    tmp = str(path) + '.tmp'
    with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as z:
        names = list(data)
        if 'mimetype' in names:
            names.remove('mimetype')
            z.writestr(zipfile.ZipInfo('mimetype'), data['mimetype'],
                       compress_type=zipfile.ZIP_STORED)
        for n in names:
            z.writestr(n, data[n])
    shutil.move(tmp, str(path))


if __name__ == '__main__':
    targets = ([Path(t) for t in sys.argv[1:]] if len(sys.argv) > 1
               else sorted(TPL.glob('*.docx')) + sorted(TPL.glob('*.odt')))
    for t in targets:
        if t.suffix == '.docx':
            add_docx(t, TPL / 'document.docx')
        elif t.suffix == '.odt':
            add_odt(t, TPL / 'document.odt')
